server:
  port: 8000

spring:
  application:
    name: cloud-order-service

# eureka
eureka:
  client:
    # 表示自己将注册eurekaserver
    register-with-eureka: false
    # 是否从eurekaserver抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka
