server:
  port: 8000

spring:
  application:
    name: cloud-consumer-consul-order

  # consul 注册中心地址
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        # hostname: 127.0.0.1
        service-name: ${spring.application.name}